version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-micro-example-db
    volumes:
      - ./.pg-vol:/var/lib/postgresql/data


  mygoapp:
    build:
      context: .  # Укажите путь к папке, где находится ваш Dockerfile
      dockerfile: Dockerfile  # Убедитесь, что имя Dockerfile указано правильно
    ports:
      - "8080:8080"  # Измените на нужный порт вашего приложения
    depends_on:
      - postgres
    