port: 8080
profile: local

config:
  source: local
  print: false

log:
  level: debug
  structured: false

db:
  name: cass
  port: 7000
  username: cass
  password: cass
  host: cass
  clean: false
  logLevel: warn


