port: 8080
profile: local

config:
  source: local
  print: false

log:
  level: debug
  structured: false

db:
  host: mongo
  port: 27017
  user: mongo
  pass: mongo
  clean: false
  logLevel: warn


